Fix printing help for missing sub-commands
Fixes error:

    AttributeError: 'Namespace' object has no attribute 'func'

Related bug report for argparse in Python 3:
http://bugs.python.org/issue16308

JIRA: PDC-2198